version: "3"

services:
  nginx:
    restart: always
    image: nginx:1.23.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./puzzling-potions/dist/:/usr/share/nginx/html/
    ports:
      - "80:80"
      - "443:443"
